# Generated by Django 3.2.4 on 2021-11-15 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='User_acA4WYFi92', max_length=100),
        ),
    ]
