# Generated by Django 3.2.4 on 2021-11-12 16:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/images/misc/')),
                ('image_url', models.URLField()),
                ('image_alt', models.CharField(max_length=200)),
                ('main_text', models.CharField(max_length=250)),
                ('sub_text', models.CharField(max_length=250)),
                ('sliding_timing', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
