# Generated by Django 3.2.4 on 2021-11-15 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscellaneous', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
